apiVersion: v1
kind: Pod
metadata:
  name: rrbench-cli
spec:
  restartPolicy: Never
  containers:
  - name: rrbench-cli
    image: kkourt/rrbench
    securityContext:
        privileged: true
        capabilities:
           add:
              - SYS_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: rrbench-srv
spec:
  restartPolicy: Never
  containers:
  - name: rrbench-srv
    image: kkourt/rrbench
